version: "3.7"
x-sockets_dev: &node_dev
  image: node:14.5.0
  volumes:
    - node__modules:/app/code/node_modules
    - .:/app/code
  working_dir: /app/code

services:
  api1:
    <<: *node_dev
    container_name: api1
    command: yarn api dev
    expose:
      - 7000
    environment:
      APP_NAME: api1
    networks:
      learning_envoy_mesh:
        aliases:
          - api1
  api2:
    <<: *node_dev
    command: yarn api dev
    container_name: api2
    expose:
      - 7000
    environment:
      APP_NAME: api2
    networks:
      learning_envoy_mesh:
        aliases:
          - api2
  sockets:
    <<: *node_dev
    command: yarn sockets dev
    container_name: sockets
    expose:
      - 7777
    environment:
      APP_NAME: api2
    networks:
      learning_envoy_mesh:
        aliases:
          - api2

  frontend:
    <<: *node_dev
    command: yarn frontend dev
    container_name: frontend
    expose:
      - 3000
    networks:
      learning_envoy_mesh:
        aliases:
          - frontend
  envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    ports:
      - 8080:8080
      - 8081:8081
      - 9901:9901
    networks:
      - learning_envoy_mesh
    volumes:
      - ./dev.envoy.yml:/etc/front-envoy.yaml
      - ./learning-envoy-crt.pem:/etc/envoy/learning-envoy-crt.pem
      - ./learning-envoy-key.pem:/etc/envoy/learning-envoy-key.pem
      - ./logs/:/etc/envoy/logs/
volumes:
  node__modules:
    external: true

networks:
  learning_envoy_mesh: {}
