version: "3.7"
x-api_dev: &api_dev
  image: node:14.5.0
  volumes:
    - node__modules:/app/code/node_modules
    - .:/app/code
  command: yarn api start
  working_dir: /app/code
x-frontend_dev: &frontend_dev
  image: node:14.5.0
  volumes:
    - node__modules:/app/code/node_modules
    - .:/app/code
  command: yarn frontend dev
  working_dir: /app/code
services:
  api1:
    <<: *api_dev
    container_name: api1
    ports:
      - 7000:7000
    expose:
      - "7000"
    environment:
      APP_NAME: api1
    networks:
      learning_envoy_mesh:
        aliases:
          - api1

  api2:
    <<: *api_dev
    container_name: api2
    expose:
      - "7000"
    environment:
      APP_NAME: api2
    networks:
      learning_envoy_mesh:
        aliases:
          - api2

  frontend:
    <<: *frontend_dev
    container_name: frontend
    ports:
      - 3000:3000
    expose:
      - "3000"
    networks:
      learning_envoy_mesh:
        aliases:
          - frontend
  envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    ports:
      - 8080:8080
      - 8081:8081
      - 9901:9901
    networks:
      - learning_envoy_mesh
    volumes:
      - ./dev.envoy.yml:/etc/front-envoy.yaml
      - ./learning-envoy-crt.pem:/etc/envoy/learning-envoy-crt.pem
      - ./learning-envoy-key.pem:/etc/envoy/learning-envoy-key.pem
      - ./logs/:/etc/envoy/logs/
volumes:
  node__modules:
    external: true

networks:
  learning_envoy_mesh: {}
